# Generated by Django 5.1.5 on 2025-01-23 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
