# Generated by Django 5.1.5 on 2025-01-23 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_profile_delete_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
