# Generated by Django 5.1.5 on 2025-01-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_storage2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage2',
            name='product',
            field=models.CharField(max_length=100),
        ),
    ]
