# Generated by Django 5.1.5 on 2025-01-30 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_storage2_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Storage2',
        ),
    ]
