# Generated by Django 5.1.5 on 2025-05-02 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_order_paypal_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paypal_order_id',
        ),
    ]
